--- #YAML:1.0
name: Net-RabbitMQ
version: 0.3.0
abstract: interface with RabbitMQ over AMQP
author:
    - Theo Schlossnagle <jesus@lethargy.org>
license: MPL
distribution_type: module
configure_requires:
    ExtUtils::MakeMaker: 0
build_requires:
    ExtUtils::MakeMaker: 0
requires:
    ExtUtils::MakeMaker: 6.03
    Test::More: 0
    Scalar::Util: 0
no_index:
    directory:
        - t
        - inc
generated_by: ExtUtils::MakeMaker version 6.50
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-v1.4.html
    version: 1.4
